apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-demo
  labels:
    app: kube-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-demo
  template:
    metadata:
      labels:
        app: kube-demo
    spec:
      containers:
        - name: kube-demo
          image: kannie/kube-demo-web:latest
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: DB_URL
              value: http://kube-demo-db.default.svc.cluster.local:8000
      tolerations:
        - key: "kwok.x-k8s.io/node"
          operator: "Exists"
          effect: "NoSchedule"
